apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: socks-shop-prod
namePrefix: prod- 
commonLabels:
  environment: socks-shop-prod

images:
- name: weaveworksdemos/user
  newTag: latest
  
bases:
- ../../base

