apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-socks-shop
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: socks-shop-tls-cert
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: front-end
          servicePort: 80